version: '3'
services:
  postgres:
    image: postgres:13
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
      POSTGRES_DB: curso_jsp
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  tomcat:
    image: tomcat:9.0
    volumes:
      - ./target/curso-jsp.war:/usr/local/tomcat/webapps/curso-jsp.war
    ports:
      - "8080:8080"

volumes:
  pgdata:
